services:

  web-server:
    build: ./services/web
    ports:
      - "80:80"

  auth-server:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    ports:
      - "3000:3000"

  problem-server:
    build: ./services/problem
    env_file:
      - ./services/problem/.env
    ports:
      - "3001:3001"

  storage-server:
    build: ./services/storage
    env_file:
      - ./services/storage/.env
    ports:
      - "3002:3002"
    volumes:
      - "./services/storage/safe:/safe"

  grade-server:
    build: ./services/grade
    env_file:
      - ./services/grade/.env
    ports:
      - "3004:3004"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  user-server:
    build: ./services/user
    env_file:
      - ./services/user/.env
    ports:
      - "3005:3005"