server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    resolver 1.1.1.1;

    location / {
        try_files $uri $uri/ /index.html;

        add_header Cross-Origin-Opener-Policy same-origin-allow-popups;
    }

    location /auth/ {
        proxy_pass http://auth-server:3000;

        proxy_ssl_server_name on;

        proxy_set_header Host auth-server:3000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location /problem/ {
        proxy_pass http://problem-server:3001;

        proxy_ssl_server_name on;

        proxy_set_header Host problem-server:3001;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location /user/ {
        proxy_pass http://user-server:3005;

        proxy_ssl_server_name on;

        proxy_set_header Host user-server:3005;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }
}